### PR TITLE
gitattributes: note that png and jpg are binary files

### PR DESCRIPTION
**Pull request by pchickey**
the assets/*.png files were getting CRLF'd up during rebases

### CODE REVIEW

**Comment by jedisct1** [comment]
Shouldn't `*.wasm` be added as well?

**Comment by jedisct1** [comment]
We have quite a few other binary files around (ex: `deploy_key.enc`, `pldi2017.pdf`). Wondering whether keeping this setting around is a good idea or if it may cause more issues that it solves.

**Comment by pchickey** [comment]
Those are in the wasm spec submodule, and haven't caused a problem so far. I'm also not sure if keeping this setting around is worthwhile, if it causes a problem again lets delete it.

**Comment by pchickey** [comment]
@freebroccolo do you have any advice on this issue?

**Comment by freebroccolo** [comment]
@pchickey This looks good. I would probably adopt most of what's in [rust-lang/rust/.gitattributes](https://raw.githubusercontent.com/rust-lang/rust/master/.gitattributes) too. I notice now that they had a comment at the end about images. Sorry I missed that in the original PR.

You also might want to have a look at some of the templates at [alexkaratarakis/gitattributes](alexkaratarakis/gitattributes).

**Pull request merged**
