### PR TITLE
Pin rustup toolchain to stable

### PR DESCRIPTION
**Pull request by freebroccolo**
This pins the rustup toolchain to "stable" within this project. This is mostly for the benefit of users that have defaulted to a different toolchain version globally and are not using the docker based environment.

### CODE REVIEW

**Comment by jedisct1** [comment]
Merged, thanks!

**Comment by freebroccolo** [comment]
Does `master` actually compile on `stable` at the moment? When I'm trying that just now I'm getting errors but it works with `nightly-2019-03-23` which I also have installed.

**Comment by jedisct1** [comment]
It should compile on `stable` if `rust-std-1.33.0-wasm32-unknown-emscripten` is also installed.

**Comment by jedisct1** [comment]
The Docker environment only includes stable version `1.33.0` and everything seems to compile just fine with it :)

**Pull request merged**
