### PR TITLE
Exit dev shell scripts on first command exiting with non-zero return

### LINKED ISSUE #279: Add a feature flag to allow excluding crypto dependencies in lucet-module-data
**Context**
This is part of a series of bugs that I spoke to @tyler @pchickey about. We are currently using  Lucet to sandbox libraries in C++ applications. The idea behind this is that using a wasm sandboxed version of the library allows ensuring that a memory safety issue in the library does not automatically result in a memory safety vulnerability in the full application. One of the  consumers of this work is the Firefox web browser. 

**Problem**
lucet-module-data provides the ability check the signature of modules prior to loading. However for the library sandboxing case, the libraries are packaged and sent together and thus have their own signing/certificate mechanisms. Thus dependencies like `minisign`, `pbkdf2`, `subtle` etc. are all unused. 

In order to simplify the dependency story here, would it make sense to add a feature flag that allows us to exclude the signing functionality? This feature flag would be enable inclusion of signing code by default, but would provide to us the ability to remove the functionality (and dependencies).

**Actions**
Please let me know your thoughts on this. If this sounds good, please also let me know if this is a change that can happen internally or if it would be better if a work on a patch that can be accepted?

### LINKED ISSUE #297: CI allows failed compilation
Referencing this comment https://github.com/fastly/lucet/pull/275#issuecomment-531299667: The CI scripts don't exit when Lucet fails to compile.

### PR DESCRIPTION
**Pull request by ekilmer**
Fixes #297

### CODE REVIEW

**Comment by jedisct1** [comment]
Hi,

This is causing scripts to immediately stop without providing much information about what happened.
 
In these scripts and depend scripts, we prefer to handle errors explicitly:

```sh
if docker ps -f name='lucet' --format '{{.Names}}' | grep -q '^lucet$' ; then
        echo "container is already running" >&2
        exit 1
fi
```

**Comment by awortman-fastly** [comment]
Yay, it fails! I'm surprised it how it fails though, it seems to fail in `devenv_run.sh` (as it should, I'd say), but Travis proceeds to continue running the CI job? That looks to be a [Travis thing](https://docs.travis-ci.com/user/job-lifecycle/#customizing-the-build-phase):

> When one of the build commands returns a non-zero exit code, the Travis CI build runs the subsequent commands as well, and accumulates the build result.

Should we have one script that does the whole build process and run that instead?

I think `set -e` on these scripts gives the failure semantics we want - there isn't error recovery to do if we fail to build the container in the first place, right? `devenv_stop.sh` afterward is messy in the build log, but it seems incorrect to run that when its dependent task, building the container, already failed.

**Comment by ekilmer** [comment]
> Travis proceeds to continue running the CI job? That looks to be a Travis thing:

Ah. I did not realize Travis would do that.

> Should we have one script that does the whole build process and run that instead?

I think it's a matter of preference, but from my experience the CI should test and run whatever actions are most likely to be executed by users of the software. If we do that, then the installation procedure is almost entirely self-documented in the CI (in case the README or Wiki directions fall out of sync).

The `devenv_run.sh` script seems to be top-most script that takes care of creating the Docker image and running the commands in the container, so I think that should be used in CI.

In terms of contributor experience, it would be nice to know that a PR doesn't pass the `indent-check` Makefile target before the `lucet` image is built, since the image takes a long time to build. This indent-check could be added to travis in `before_script`.

Please review the changes in https://github.com/fastly/lucet/pull/298/commits/93e4e6e62c9ab49fd48a2095ff4a3f0f3b0cf6b2 for Travis reorganization. All of this, assuming this commit behaves in Travis how I think it will behave

**Comment by jedisct1** [comment]
`|| travis_terminate 1` looks like the best way to handle this.

So we don't need `set -e` any more.

**Comment by ekilmer** [comment]
@jedisct1 The CI is supposed to fail because of the compilation error, but it doesn't when I remove the `set -e`. Which means the `set -e` is still needed in order to propagate the error in the devenv start script to the devenv run script.

**Comment by ekilmer** [comment]
Master is still failing https://travis-ci.org/fastly/lucet/jobs/585003700#L2256

**Comment by jedisct1** [comment]
Error handling is missing in `devenv_build_container.sh`.

**Pull request merged**
